### PR TITLE
ci: use github actions with platformio

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
pr success: https://github.com/thijstriemstra/TCA9548A/runs/2052805370 @WifWaf 

can you also enable github actions for this repo?

**Comment by thijstriemstra** [comment]
ping @WifWaf

**Comment by WifWaf** [comment]
Not entirely sure how this works...
Will the script impact non uno and d1_mini and lolin32 users?

**Comment by thijstriemstra** [comment]
this script verifies if the example/library properly compiles for those specified boards. compiler errors will fail the remote build and alert you. it's an easy way to test against multiple boards.

**Comment by thijstriemstra** [comment]
and no, it doesn't affect those users.

**Comment by WifWaf** [comment]
Sounds goods, I'll merge and have a further read.

**Pull request merged**
